### ISSUE TITLE
依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Harasou21** [Harasou21/furima-28610#8]
[本番環境のURL](https://furima-28610.herokuapp.com)
Basic認証のID:  admin,password: 2222
出品者用のメアドとパスワード
メアド、harasou413soccer@gmail.com,password: xxxxxx123
購入者用のメアドとパスワード
メアド、harasou414soccer@gmail.com,password: xxxxxx123
購入者カード番号、4242424242424242,有効期限 12/24,cvc 123

**Comment by cb-fu** [comment]
原さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

[修正箇所]
登録した内容でログインしようとしても、ログインすることができません。
※下記画像参照

<img width="1222" alt="スクリーンショット 2020-11-05 18 19 25" src="https://user-images.githubusercontent.com/64946918/98222274-f66e2800-1f93-11eb-8bd6-1d86c7cebbb5.png">




修正し次第、以下の最終課題完了報告フォームを再度提出お願いします！
※新しいissueを作っていただく必要はありません
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Harasou21** [comment]
修正できたと思います！ご確認のほどよろしくお願いします！

**Comment by erinasan1029** [comment]
原さん、ご提出ありがとうございます！

修正できていらっしゃいました！

また、挙動確認もさせて頂きましたが、
全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**

**Comment by Harasou21** [comment]
ありがとうございました！
